version: '3.5'

services:
  rio.api:
    build:
      dockerfile: Rio.API/LocalDockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - KEYSTONE_HOST=${KEYSTONE_HOST}
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SITKA_EMAIL_REDIRECT=${SITKA_EMAIL_REDIRECT}
      - WEB_URL=${WEB_URL}
      - SECRET_PATH=${SECRET_PATH}
      - KEYSTONE_REDIRECT_URL=${KEYSTONE_REDIRECT_URL}
      - ALLOW_TRADING=${ALLOW_TRADING}
      - PlatformLongName=${PlatformLongName}
      - PlatformShortName=${PlatformShortName}
      - LeadOrganizationLongName=${LeadOrganizationLongName}
      - LeadOrganizationShortName=${LeadOrganizationShortName}
      - LeadOrganizationHomeUrl=${LeadOrganizationHomeUrl}
      - LeadOrganizationEmail=${LeadOrganizationEmail}
      - VerificationKeyChars=${VerificationKeyChars}
      - ValidParcelNumberRegexPattern=${ValidParcelNumberRegexPattern}
      - ValidParcelNumberPatternAsStringForDisplay=${ValidParcelNumberPatternAsStringForDisplay}
      - OpenETAPIBaseUrl=${OpenETAPIBaseUrl}
      - OpenETRasterTimeSeriesMultipolygonRoute=${OpenETRasterTimeSeriesMultipolygonRoute}
      - OpenETRasterMetadataRoute=${OpenETRasterMetadataRoute}
      - OpenETRasterExportStatusRoute=${OpenETRasterExportStatusRoute}
      - OpenETGoogleBucketBaseURL=${OpenETGoogleBucketBaseURL}
      - OpenETRasterMetadataBoundingBoxLeft=${OpenETRasterMetadataBoundingBoxLeft}
      - OpenETRasterMetadataBoundingBoxRight=${OpenETRasterMetadataBoundingBoxRight}
      - OpenETRasterMetadataBoundingBoxTop=${OpenETRasterMetadataBoundingBoxTop}
      - OpenETRasterMetadataBoundingBoxBottom=${OpenETRasterMetadataBoundingBoxBottom}
      - OpenETRasterTimeseriesMultipolygonColumnToUseAsIdentifier=${OpenETRasterTimeseriesMultipolygonColumnToUseAsIdentifier}
      - AllowOpenETSync=${AllowOpenETSync}
      - SupportEmailAddress=${SupportEmailAddress}
      - APPINSIGHTS_INSTRUMENTATIONKEY=${APPINSIGHTS_INSTRUMENTATIONKEY}
      - Ogr2OgrExecutable=${Ogr2OgrExecutable}
      - OgrInfoExecutable=${OgrInfoExecutable}
